/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AutorNomeRouteImport } from './routes/autor.$nome'
import { Route as PostagemIndexRouteImport } from './routes/postagem.$index'
import { Route as ApiPublicSplatRouteImport } from './routes/api/public/$'
import { Route as ApiPublicAutoresRouteImport } from './routes/api/public/autores'
import { Route as ApiPublicBuscarRouteImport } from './routes/api/public/buscar'
import { Route as ApiPublicCategoriasRouteImport } from './routes/api/public/categorias'
import { Route as ApiPublicPostagensRouteImport } from './routes/api/public/postagens'
import { Route as ApiPublicAutorNomeRouteImport } from './routes/api/public/autor.$nome'
import { Route as ApiPublicCategoriaCategoriaRouteImport } from './routes/api/public/categoria.$categoria'
import { Route as ApiPublicPostagemIndexRouteImport } from './routes/api/public/postagem.$index'
import { Route as ApiPublicPostagensDestaquesRouteImport } from './routes/api/public/postagens.destaques'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AutorNomeRoute = AutorNomeRouteImport.update({
  id: '/autor/$nome',
  path: '/autor/$nome',
  getParentRoute: () => rootRouteImport,
} as any)
const PostagemIndexRoute = PostagemIndexRouteImport.update({
  id: '/postagem/$index',
  path: '/postagem/$index',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicSplatRoute = ApiPublicSplatRouteImport.update({
  id: '/api/public/$',
  path: '/api/public/$',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicAutoresRoute = ApiPublicAutoresRouteImport.update({
  id: '/api/public/autores',
  path: '/api/public/autores',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicBuscarRoute = ApiPublicBuscarRouteImport.update({
  id: '/api/public/buscar',
  path: '/api/public/buscar',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicCategoriasRoute = ApiPublicCategoriasRouteImport.update({
  id: '/api/public/categorias',
  path: '/api/public/categorias',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicPostagensRoute = ApiPublicPostagensRouteImport.update({
  id: '/api/public/postagens',
  path: '/api/public/postagens',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicAutorNomeRoute = ApiPublicAutorNomeRouteImport.update({
  id: '/api/public/autor/$nome',
  path: '/api/public/autor/$nome',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicCategoriaCategoriaRoute =
  ApiPublicCategoriaCategoriaRouteImport.update({
    id: '/api/public/categoria/$categoria',
    path: '/api/public/categoria/$categoria',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicPostagemIndexRoute = ApiPublicPostagemIndexRouteImport.update({
  id: '/api/public/postagem/$index',
  path: '/api/public/postagem/$index',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicPostagensDestaquesRoute =
  ApiPublicPostagensDestaquesRouteImport.update({
    id: '/destaques',
    path: '/destaques',
    getParentRoute: () => ApiPublicPostagensRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/autor/$nome': typeof AutorNomeRoute
  '/postagem/$index': typeof PostagemIndexRoute
  '/api/public/$': typeof ApiPublicSplatRoute
  '/api/public/autores': typeof ApiPublicAutoresRoute
  '/api/public/buscar': typeof ApiPublicBuscarRoute
  '/api/public/categorias': typeof ApiPublicCategoriasRoute
  '/api/public/postagens': typeof ApiPublicPostagensRouteWithChildren
  '/api/public/autor/$nome': typeof ApiPublicAutorNomeRoute
  '/api/public/categoria/$categoria': typeof ApiPublicCategoriaCategoriaRoute
  '/api/public/postagem/$index': typeof ApiPublicPostagemIndexRoute
  '/api/public/postagens/destaques': typeof ApiPublicPostagensDestaquesRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/autor/$nome': typeof AutorNomeRoute
  '/postagem/$index': typeof PostagemIndexRoute
  '/api/public/$': typeof ApiPublicSplatRoute
  '/api/public/autores': typeof ApiPublicAutoresRoute
  '/api/public/buscar': typeof ApiPublicBuscarRoute
  '/api/public/categorias': typeof ApiPublicCategoriasRoute
  '/api/public/postagens': typeof ApiPublicPostagensRouteWithChildren
  '/api/public/autor/$nome': typeof ApiPublicAutorNomeRoute
  '/api/public/categoria/$categoria': typeof ApiPublicCategoriaCategoriaRoute
  '/api/public/postagem/$index': typeof ApiPublicPostagemIndexRoute
  '/api/public/postagens/destaques': typeof ApiPublicPostagensDestaquesRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/autor/$nome': typeof AutorNomeRoute
  '/postagem/$index': typeof PostagemIndexRoute
  '/api/public/$': typeof ApiPublicSplatRoute
  '/api/public/autores': typeof ApiPublicAutoresRoute
  '/api/public/buscar': typeof ApiPublicBuscarRoute
  '/api/public/categorias': typeof ApiPublicCategoriasRoute
  '/api/public/postagens': typeof ApiPublicPostagensRouteWithChildren
  '/api/public/autor/$nome': typeof ApiPublicAutorNomeRoute
  '/api/public/categoria/$categoria': typeof ApiPublicCategoriaCategoriaRoute
  '/api/public/postagem/$index': typeof ApiPublicPostagemIndexRoute
  '/api/public/postagens/destaques': typeof ApiPublicPostagensDestaquesRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/autor/$nome'
    | '/postagem/$index'
    | '/api/public/$'
    | '/api/public/autores'
    | '/api/public/buscar'
    | '/api/public/categorias'
    | '/api/public/postagens'
    | '/api/public/autor/$nome'
    | '/api/public/categoria/$categoria'
    | '/api/public/postagem/$index'
    | '/api/public/postagens/destaques'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/autor/$nome'
    | '/postagem/$index'
    | '/api/public/$'
    | '/api/public/autores'
    | '/api/public/buscar'
    | '/api/public/categorias'
    | '/api/public/postagens'
    | '/api/public/autor/$nome'
    | '/api/public/categoria/$categoria'
    | '/api/public/postagem/$index'
    | '/api/public/postagens/destaques'
  id:
    | '__root__'
    | '/'
    | '/autor/$nome'
    | '/postagem/$index'
    | '/api/public/$'
    | '/api/public/autores'
    | '/api/public/buscar'
    | '/api/public/categorias'
    | '/api/public/postagens'
    | '/api/public/autor/$nome'
    | '/api/public/categoria/$categoria'
    | '/api/public/postagem/$index'
    | '/api/public/postagens/destaques'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AutorNomeRoute: typeof AutorNomeRoute
  PostagemIndexRoute: typeof PostagemIndexRoute
  ApiPublicSplatRoute: typeof ApiPublicSplatRoute
  ApiPublicAutoresRoute: typeof ApiPublicAutoresRoute
  ApiPublicBuscarRoute: typeof ApiPublicBuscarRoute
  ApiPublicCategoriasRoute: typeof ApiPublicCategoriasRoute
  ApiPublicPostagensRoute: typeof ApiPublicPostagensRouteWithChildren
  ApiPublicAutorNomeRoute: typeof ApiPublicAutorNomeRoute
  ApiPublicCategoriaCategoriaRoute: typeof ApiPublicCategoriaCategoriaRoute
  ApiPublicPostagemIndexRoute: typeof ApiPublicPostagemIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/autor/$nome': {
      id: '/autor/$nome'
      path: '/autor/$nome'
      fullPath: '/autor/$nome'
      preLoaderRoute: typeof AutorNomeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/postagem/$index': {
      id: '/postagem/$index'
      path: '/postagem/$index'
      fullPath: '/postagem/$index'
      preLoaderRoute: typeof PostagemIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/$': {
      id: '/api/public/$'
      path: '/api/public/$'
      fullPath: '/api/public/$'
      preLoaderRoute: typeof ApiPublicSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/autores': {
      id: '/api/public/autores'
      path: '/api/public/autores'
      fullPath: '/api/public/autores'
      preLoaderRoute: typeof ApiPublicAutoresRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/buscar': {
      id: '/api/public/buscar'
      path: '/api/public/buscar'
      fullPath: '/api/public/buscar'
      preLoaderRoute: typeof ApiPublicBuscarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/categorias': {
      id: '/api/public/categorias'
      path: '/api/public/categorias'
      fullPath: '/api/public/categorias'
      preLoaderRoute: typeof ApiPublicCategoriasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/postagens': {
      id: '/api/public/postagens'
      path: '/api/public/postagens'
      fullPath: '/api/public/postagens'
      preLoaderRoute: typeof ApiPublicPostagensRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/autor/$nome': {
      id: '/api/public/autor/$nome'
      path: '/api/public/autor/$nome'
      fullPath: '/api/public/autor/$nome'
      preLoaderRoute: typeof ApiPublicAutorNomeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/categoria/$categoria': {
      id: '/api/public/categoria/$categoria'
      path: '/api/public/categoria/$categoria'
      fullPath: '/api/public/categoria/$categoria'
      preLoaderRoute: typeof ApiPublicCategoriaCategoriaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/postagem/$index': {
      id: '/api/public/postagem/$index'
      path: '/api/public/postagem/$index'
      fullPath: '/api/public/postagem/$index'
      preLoaderRoute: typeof ApiPublicPostagemIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/postagens/destaques': {
      id: '/api/public/postagens/destaques'
      path: '/destaques'
      fullPath: '/api/public/postagens/destaques'
      preLoaderRoute: typeof ApiPublicPostagensDestaquesRouteImport
      parentRoute: typeof ApiPublicPostagensRoute
    }
  }
}

interface ApiPublicPostagensRouteChildren {
  ApiPublicPostagensDestaquesRoute: typeof ApiPublicPostagensDestaquesRoute
}

const ApiPublicPostagensRouteChildren: ApiPublicPostagensRouteChildren = {
  ApiPublicPostagensDestaquesRoute: ApiPublicPostagensDestaquesRoute,
}

const ApiPublicPostagensRouteWithChildren =
  ApiPublicPostagensRoute._addFileChildren(ApiPublicPostagensRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AutorNomeRoute: AutorNomeRoute,
  PostagemIndexRoute: PostagemIndexRoute,
  ApiPublicSplatRoute: ApiPublicSplatRoute,
  ApiPublicAutoresRoute: ApiPublicAutoresRoute,
  ApiPublicBuscarRoute: ApiPublicBuscarRoute,
  ApiPublicCategoriasRoute: ApiPublicCategoriasRoute,
  ApiPublicPostagensRoute: ApiPublicPostagensRouteWithChildren,
  ApiPublicAutorNomeRoute: ApiPublicAutorNomeRoute,
  ApiPublicCategoriaCategoriaRoute: ApiPublicCategoriaCategoriaRoute,
  ApiPublicPostagemIndexRoute: ApiPublicPostagemIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
